### ISSUE TITLE
export2graphlan error

### ISSUE THREAD

**Issue by ZhangMin-123** [SegataLab/export2graphlan#4]
Hi,

I'm trying to use export2graphlan on my humann3 abundance table output.  but when I RUN:
"Traceback (most recent call last):
  File "/home/meta/miniconda2/envs/meta/bin/export2graphlan.py", line 768, in <module>
    main()
  File "/home/meta/miniconda2/envs/meta/bin/export2graphlan.py", line 511, in main
    lefse_input = DataMatrix(args.lefse_input, args)
  File "/home/meta/miniconda2/envs/meta/bin/hclust2.py", line 149, in __init__
    index_col = self.args.sname_row if self.args.sname_row > -1 else None
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 1886, in read
    values = data.pop(self.index_col[i])
IndexError: list index out of range".
[物种.xlsx](https://github.com/SegataLab/export2graphlan/files/7901922/default.xlsx)

Any ideas what's going wrong?
Thanks in advance!

**Comment by fasnicar** [comment]
Hi, can you please provide the full command and also the input file(s) you're using?

**Comment by ZhangMin-123** [comment]
> 

export2graphlan.py --skip_rows 1,2 -i taxonomy.tsv \
>       --tree temp/merged_abundance.tree.txt \
>       --annotation temp/merged_abundance.annot.txt \
>       --most_abundant 1000 --abundance_threshold 20 --least_biomarkers 10 \
>       --annotations 3,4 --external_annotations 7
Traceback (most recent call last):
  File "/home/meta/miniconda2/envs/meta/bin/export2graphlan.py", line 768, in <module>
    main()
  File "/home/meta/miniconda2/envs/meta/bin/export2graphlan.py", line 511, in main
    lefse_input = DataMatrix(args.lefse_input, args)
  File "/home/meta/miniconda2/envs/meta/bin/hclust2.py", line 149, in __init__
    index_col = self.args.sname_row if self.args.sname_row > -1 else None
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/home/meta/miniconda2/envs/meta/lib/python2.7/site-packages/pandas/io/parsers.py", line 1886, in read
    values = data.pop(self.index_col[i])
IndexErro[taxonomy.xlsx](https://github.com/SegataLab/export2graphlan/files/7911565/taxonomy.xlsx)

**Comment by timj6599** [comment]
i got the same error. any fixes?

**Comment by fasnicar** [comment]
It could be due to the presence of the `NCBI_tax_ID` column. Can you check if removing it will solve it? In this case, I can implement a code fix for this case.

Thanks,
Francesco
